name: AirBridge
version: "1.0.0"
slug: airbridge
description: AirPlay to Amazon Echo over Bluetooth
url: https://github.com/PhilippV22/alexa-airplay
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
host_network: true
host_dbus: true
privileged:
  - NET_ADMIN
  - NET_RAW
apparmor: false
options:
  log_level: info
  adapter: hci0
  reconnect_interval_seconds: 15
  airplay_port_base: 5500
  udp_port_base: 20000
  targets: []
schema:
  log_level: list(trace|debug|info|warning|error)
  adapter: str
  reconnect_interval_seconds: int(5,300)
  airplay_port_base: port
  udp_port_base: port
  targets:
    - name: str
      airplay_name: str
      mac: match(^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$)
      enabled: bool
